name:                icfpc2022
version:             0.1.0.0
github:              "codingteam/icfpc-2022"
license:             MIT
author:              "Codingteam"
maintainer:          "example@example.com"
copyright:           "2022 Codingteam"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/codingteam/icfpc-2022#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- array
- binary
- bits
- bytes
- bytestring
- containers
- hashable
- mtl
- text
- time
- unordered-containers
- utf8-string
- vector
- JuicyPixels
- JuicyPixels-extra
- deepseq
- gloss
- gloss-juicy
- parallel

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  icfpc2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - icfpc2022

tests:
  icfpc2022-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2022
    - hspec
    - tasty
    - tasty-hunit
